# @package _global_
module:
  _target_: emg2qwerty.lightning.ConvGRUConvCTCModule
  in_features: 528
  mlp_features: [384]
  hidden_size: 384
  num_layers: 2
  conv_kernel_size: 31
  dropout: 0.1

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 16000
  padding: [900, 100]
