# @package _global_
module:
  _target_: emg2qwerty.lightning.CRNNCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  cnn_block_channels: [24, 24]
  cnn_kernel_width: 32  # Temporal shrinkage: 2 * (kernel_width - 1) = 16
  rnn_hidden_size: 512
  rnn_num_layers: 3
  rnn_bidirectional: true
  rnn_nonlinearity: tanh
  rnn_dropout: 0.0

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
