# Raw CNN+GRU with CTC. Raw EMG input (no spectrogram).
# @package _global_
module:
  _target_: emg2qwerty.lightning.RawCnnGruCtcModule
  # cnn_channels: [64, 128, 192]
  cnn_channels: [96, 192, 256]
  # cnn_channels: [128,256,384]
  cnn_kernel_sizes: [9, 9, 9]
  cnn_strides: [3, 4, 4]  # Product 48 to mirror hop_length=48 resolution
  cnn_paddings: [4, 4, 4]  # "same-ish" temporal padding for stable shrinkage
  cnn_dilations: [1, 1, 1]
  cnn_use_batch_norm: true
  gru_hidden_size: 384
  gru_num_layers: 2
  gru_bidirectional: true
  gru_dropout: 0.5

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 20000
  stride: 12000  # around 50% overlap
  padding: [900, 200]  # 900ms past context, 100ms future context
