# @package _global_
# Preprocessing ablation: heavier SpecAugment
defaults:
  - log_spectrogram

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 5
  time_mask_param: 40
  n_freq_masks: 3
  freq_mask_param: 6
